### ISSUE TITLE
Review "GP/Gas Fee" labels and tooltips

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#314]
In GP swap  the Fees are labeled as GP/Gas Fee. To have it consistent it might be good to have the same wording for the explorer.
![Bildschirmfoto 2021-03-17 um 11 28 31](https://user-images.githubusercontent.com/34510341/111453824-487a4380-8714-11eb-9804-b7d2bf821bed.png)
<img width="702" alt="Bildschirmfoto 2021-03-17 um 11 28 37" src="https://user-images.githubusercontent.com/34510341/111453850-4dd78e00-8714-11eb-8ebc-0115e07e44c2.png">

## Tasks
(Mareen, I edited your issue to describe what we will do, moving this to our backlog)
* [ ] Review Swap UI, for labels and tooltips referring to the fee. Make sure we are consistent. Instead of "GP/Gas Fee" we can say "Protocol/Gas Fee". The hover should say `The gas fees for this trade are already included in your receiving balance. You don't need ETH for this trade.` as per @annamsgeorge suggestion.
* [ ] Do the same in the Explorer

**Comment by anxolin** [comment]
Yes, "GP/Gas Fee" everywhere sounds good to me. Good catch

**Comment by annamsgeorge** [comment]
Note that we will probably reword this, as in CowSwap we should not call it "GP" fees - nobody knows what GP is :)

**Comment by anxolin** [comment]
@annamsgeorge is best to make an issue for the rewording. I can do it, but I think you want to add a few other things. Alternativelly, you can add it as details for the issue of #206 (somewhat related)

**Comment by anxolin** [comment]
@annamsgeorge one thing to note, is that in one interview, someone mentioned that is also nice to explain how much is this fee in the tooltip. Like a percentage, however, I'm happy with your tooltip proposal since we don't have a super easy to understand answer. 

I would rather show the USD estimation, so they get a better understanding how much it is. Actually, I think the estimation is quite important, specially if we subsidize. Otherwise, people don't really appreciate how much they save by using GP.

**Comment by annamsgeorge** [comment]
Proposal: (let me know if I should open a new issue for this!) 

In the UI it should say: 
"Protocol/Gas fee". 

In the hover text it should say:
"All fees (incl. gas fees) are already included in your receiving balance. You don't need ETH for this trade."

**Comment by annamsgeorge** [comment]
Update: I created a new issue for this: #335

**Comment by anxolin** [comment]
this should be done already! 
Anyone open this if you find any instance of unhandled messages
