### ISSUE TITLE
Cancel order: Sync statuses in Explorer and CowSwap

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#612]
The issue is related to the 'Cancel' order transactions.

When I cancel an order, it is immediately changes its status as 'Cancelled' in the  protocol explorer.
However, as we use a 'soft' cancellation, the order might be executed, hence, the status is changed to 'Filled' in the explorer, and it seems to be strange a bit. 
I think it would be nice to add 'Cancelling' status in the protocol explorer (link it is in the CowSwap app) for an order and show it until an order is successfully cancelled/filled.
https://drive.google.com/file/d/1j92oV8O2LLPMGZgCY4FSUnFZrXXhjpVL/view

**Comment by anxolin** [comment]
@elena-zh u are super good at testing edge cases 💪

> With a new sidebar implementation now it looks odd when 'valid to' time is less than a current one, but the order is still in 'Open' status..

I think this should only happen for a few seconds, then should expire. This is because we only update periodically. It can be improved if we actually set a timer instead of periodically update. However, i would consider it low prio. If we want to keep track of that we can make an independent issue for it. 

> One more issue related to statuses in Explorer: my transaction time has expired, however, status is still 'Open"..

I think is similar to the previous case. We could also do a similar solution. Also, im not too concerned with this one for now. But true that it might be a good idea to track it. 


> Sometimes, I see the notification message in the CowSwap app that my transaction is successfully cancelled.
However, in a few seconds, I may receive a notification about the successful order placement.
Looks a bit confusing to me..

This one is more annoying 😅
I think we should fix it, not too urgent, but I think this one should be in it's own issue because is unrelated to the others. Is likely that we already have it, or we have one very similar.

**Comment by anxolin** [comment]
#612 I think could potentially be 4 issues. 1 i think is important to solve eventually. Then there’s issues related to the canceled state having a small delay (that is fine for now imo, but can be improved).

Then there’s the issue of CowSwap / Explorer discrepancy on CANCEL workflow. CowSwap has “canceling state”. I understand why we did it differently, but I would argue that is more important to be coherent.

**Comment by elena-zh** [comment]
> I think this should only happen for a few seconds, then should expire.

If only for a few seconds... 
This happens for a minute or so. That's why I'm reporting this issue=)

**Comment by anxolin** [comment]
> This happens for a minute or so. That's why I'm reporting this issue=)

ohh, ok! then we should definitely review. Thanks for raising it. At least we could make the check more frequent, that would be a quick fix

**Comment by elena-zh** [comment]
Yes, For convenience, I can create a separate issue for this case
